### ISSUE TITLE
Doesn't work on pull requests that don't have the `mergeability-details` container at the bottom

### ISSUE THREAD

**Issue by evanlucas** [evanlucas/node-review#1]
With the transition to the new review based system, some pull requests do not have a div with the `mergeability-details` class. This class is what we currently use for the new reviews.

A workaround could be to look in the comments that are approval comments?

**Comment by thefourtheye** [comment]
You mean when there is a merge conflict?

**Comment by evanlucas** [comment]
No, there are a few pull requests that I tried it on that did not have the container at the bottom of the PR. Now that I am trying to find one though, I'm having trouble. I'll keep looking and update when I do find one.

**Comment by evanlucas** [comment]
ok, so I'm really not sure what's going on now as https://github.com/nodejs/node/pull/9041 works in Chrome 52, but doesn't show all reviewers in Chrome 53. I'll keep digging

**Comment by evanlucas** [comment]
This should be fixed now.
