### ISSUE TITLE
seems to not account for when a review has been dismissed

### ISSUE THREAD

**Issue by sam-github** [evanlucas/node-review#14]
example: https://github.com/nodejs/node/pull/10747

![a](https://user-images.githubusercontent.com/17607/30185258-914e3e76-93d5-11e7-951b-88ffd98179bb.png)

![b](https://user-images.githubusercontent.com/17607/30185265-973f0108-93d5-11e7-8976-1ad5c204d549.png)

**Comment by refack** [comment]
I just encountered that and patched it yesterday 😄.
Just opened PR https://github.com/evanlucas/node-review/pull/15

**Comment by joyeecheung** [comment]
Looks like it still doesn't handle https://github.com/nodejs/node/pull/14782 when someone dissmised their own reviews

**Comment by joyeecheung** [comment]
Funny enough, it also tries to delete my review (not that I have approved or rejected at that point) from the map when I added a reference with a title containing "dismissed" lol

**Comment by sam-github** [comment]
Looks like @joyeecheung fixed this in #16 (but it can be reopened if that is not the case).
