### ISSUE TITLE
Feature request: check for CI runs

### ISSUE THREAD

**Issue by joyeecheung** [evanlucas/node-review#18]
* If there are commits pushed after the last CI link has been posted, warn about it
* If there are no CI runs and this is not a doc-only change, warn about it

**Comment by vsemozhetbyt** [comment]
A nit: doc-only PRs need linting CI if they contain code fragments, And if https://github.com/nodejs/node/pull/16208 makes it only as a simple part of tests, doc-only PRs will need complete CI.
