### ISSUE TITLE
claims that PR is not accepted yet

### ISSUE THREAD

**Issue by sam-github** [evanlucas/node-review#8]
Oh, no! I don't think I can live without node-review anymore, and its not working for me with https://github.com/nodejs/node/pull/5923

It claims

```
Error: This pull request is not yet ready to land. 
The following reviewers have requested changes: 
```

Yes, that is the empty list, because all reviewers have accepted the changes. Just me, or is it a problem for other people? I haven't landed any changes for almost 2 weeks (vacation, travel), so I don't know if this is new or not.

I wonder if its coincidental that I recently reported a bug to github where some reviewers listed in the conversation review summary at the bottom of the thread were not listed in the review area at the top-right of the page, a problem they fixed a week or so ago.

**Comment by vsemozhetbyt** [comment]
I see a proper result there:
```
PR Metadata

PR-URL: https://github.com/nodejs/node/pull/5923
Reviewed-By: Ben Noordhuis <info@bnoordhuis.nl>
Reviewed-By: Colin Ihrig <cjihrig@gmail.com>
Reviewed-By: Sam Roberts <vieuxtech@gmail.com>
Reviewed-By: James M Snell <jasnell@gmail.com>
```
Google Chrome 59.0.3048.0 Canary

**Comment by evanlucas** [comment]
Are you using the latest version? That pr did not work for either until I pulled the latest from master and then reloading the extension.

**Comment by sam-github** [comment]
That was the issue, out of date, thanks. I forgot that this hadn't been installed normally, and the extension doesn't auto-update. Its working after update.

**Comment by evanlucas** [comment]
Glad you got it working. I really need to get it published to the chrome app store, just haven't had a chance to. I'll try to do that sometime this week or next...
